Remove unnecessary (and non-compliant) use of property overrides.
BHoM/XML_Toolkit pull request #521
Opened 2021-01-14 16:50 UTC by rolyhudson

### Issues addressed by this PR

 Closes #520 

 
All instances of `public new string ID` removed - this was an unnecessary in all cases as the property is inherited from the base class.

 ### Test files

Can be tested following procedure described [here](https://burohappold.sharepoint.com/:w:/r/sites/BHoM/01_Master%20File/09_QAQC/04%20-%20Testing%20Procedures/0010_Transdisciplinary/0001_XML_Toolkit.docx?d=w929c5e38063d427e920f8edffc8722bb&csf=1&web=1&e=focuNh)

 ### Changelog

 ### Additional comments

2021-01-14 17:07 UTC, FraserGreenroyd requested changes
@rolyhudson wasn't the plan to also make the properties virtual, or have we not done that for the gbXML objects?

If we didn't do it for the gbXML ones then I'm happy to approve and merge this. If we did it for the gbXML ones, we should probably do it for the KML ones too?

2021-01-15 08:21 UTC, rolyhudson commented
@FraserGreenroyd I may have missed part of the conversation on this or misunderstood. 
But, right now the bgXML schema objects don't have properties as `virtual`.
KML schema objects align with this.
But if the idea was to use `virtual` across all those schema objects I would happily do so across the the Toolkit.
Description in #520 could be interpreted in this way. But we should update the the title of the issue and this PR to reflect that.

2021-01-15 08:31 UTC, FraserGreenroyd approved these changes
No worries @rolyhudson , I'm happy with alignment with the gbXML schema :smile:

2021-01-15 08:31 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-01-15 08:49 UTC, merged