Zero length string now handled for the Depth property
BHoM/XML_Toolkit pull request #555
Opened 2022-05-24 11:32 UTC by jamesramsden-bh

Closes #554 

 

 ### Test files

Try different values of 'depth' in the XML file. Verify the value of 'Depth' in the exploded markup. 
[test.zip](https://github.com/BHoM/XML_Toolkit/files/8762243/test.zip)

 ### Changelog

 ### Additional comments

2022-05-24 11:59 UTC, rboulton-BH submitted a review, later dismissed
I've tested the updated code using the sample dwelling and script which is referenced in the original issue. Looks like it's working well now with these changes

2022-05-24 12:01 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-11-23 11:40 UTC, jamesramsden-bh commented
@BHoMBot check compliance

2022-11-23 11:42 UTC, jamesramsden-bh commented
@BHoMBot check compliance

2022-11-23 11:45 UTC, jamesramsden-bh commented
@BHoMBot check required

2022-11-23 11:55 UTC, EKAdebo submitted a review, later dismissed
Looks like it's working, the data from XML files is coming through as expected.

2022-11-23 12:48 UTC, jamesramsden-bh commented
@BHoMBot check ready-to-merge

2022-11-23 12:49 UTC, jamesramsden-bh commented
@BHoMBot check ready-to-merge

2022-11-24 10:18 UTC, FraserGreenroyd requested changes
As discussed on a call with @jamesramsden-bh and @CKBoulter just now, agreement to add a `Query` method to query the double depth to support numerical workflows.

```
public static double Depth(this Markup markup)
{
    try
    {
        return System.Convert.ToDouble(markup.XMLDepth);
    }
    catch(Exception e)
    {
        BH.Engine.Base.Compute.RecordError("Could not convert XMLDepth to numerical depth.");
        return -1;
    }
}
```

@rboulton-BH @EKAdebo is a return of `-1` for a failed depth suitable here?

2022-11-24 12:33 UTC, FraserGreenroyd requested changes
See comments @CKBoulter @jamesramsden-bh

2022-11-24 12:33 UTC, FraserGreenroyd commented on XML_Engine/Query/Depth.cs
> +        [Description("Determines whether a collection of Environment Panels representing a single space contains any panels which are externally facing")]
👀 are you sure?

2022-11-24 12:33 UTC, FraserGreenroyd commented on XML_Engine/Query/Depth.cs
> +        [Output("isExternal", "True if the space has at least one externally facing Panel")]
I suspect this might be a copy-paste that wasn't updated 😉

2022-11-24 12:33 UTC, FraserGreenroyd commented on XML_Engine/XML_Engine.csproj
> +      <HintPath>..\..\..\ProgramData\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
```suggestion
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
```

2022-11-24 12:33 UTC, FraserGreenroyd commented on XML_Engine/XML_Engine.csproj
> +      <HintPath>..\..\..\ProgramData\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
Will need further compliance on specific version which the bot will pick up for us.

2022-11-24 18:33 UTC, FraserGreenroyd requested changes

2022-11-24 18:33 UTC, FraserGreenroyd commented on XML_Engine/Query/Depth.cs
> +        [Description("Returns the 'depth' property of a markup object as a double. If the value cannot be converted to a double (if the value is null or blank for example) then an error will be retur
```suggestion
        [Description("Returns the 'depth' property of a markup object as a double. If the value cannot be converted to a double (if the value is null or blank for example) then an error will be provided and -1 will be returned.")]
```

2022-11-24 18:33 UTC, FraserGreenroyd commented on XML_Engine/Query/Depth.cs
> +        [Output("Depth", "The depth value as a double, or -1 if the value could not be converted to a double.")]
```suggestion
        [Output("depth", "The depth value as a double, or -1 if the value could not be converted to a double.")]
```

2022-11-24 18:45 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-11-24 18:48 UTC, CKBoulter commented
@BHoMBot fix project file ref. 9695000940

2022-11-24 18:49 UTC, FraserGreenroyd commented
@BHoMBot fix project file ref. 9695000940

2022-11-24 18:49 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-11-24 18:52 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-11-24 19:22 UTC, FraserGreenroyd commented
@BHoMBot check null-handling

2022-11-24 19:24 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check required

2022-11-24 21:12 UTC, FraserGreenroyd approved these changes
Functionality remains the same following @EKAdebo review, new method looks good and works well. Happy to merge to alpha.

2022-11-24 21:12 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-11-24 23:12 UTC, merged