Refactor adapter to be in line with other adapters
BHoM/XML_Toolkit pull request #593
Opened 2023-10-25 15:05 UTC by Tom-Kingstone

### Issues addressed by this PR

 Closes #592 

 
- File settings attribute removed from `XMLAdapter` and placed in `XMLConfig`.
- `XMLConfig` is now an `IXMLConfig` and any future configs must contain a file settings attribute.
- CRUD methods have been updated to use `config.File` rather than `_fileSettings`

2023-10-25 15:06 UTC, Tom-Kingstone commented
@BHoMBot check compliance

2023-10-25 15:09 UTC, FraserGreenroyd requested changes
Looks like I set up the settings nicely the last time so this wasn't as much work as I was expecting!

Minor changes needed please @Tom-Kingstone

2023-10-25 15:09 UTC, FraserGreenroyd commented on XML_Adapter/XMLAdapter.cs
> +        public XMLAdapter()
Needs versioning please

2023-10-25 15:18 UTC, Tom-Kingstone commented
@BHoMBot check compliance
@BHoMBot check versioning

2023-10-25 15:27 UTC, FraserGreenroyd requested changes

2023-10-25 15:27 UTC, FraserGreenroyd commented on XML_Adapter/XMLAdapter.cs
> +        [PreviousVersion("7.0", "BH.Adapter.XML.XMLAdapter(BH.oM.Adapter.Filesettings)")]
```suggestion
        [PreviousVersion("7.0", "BH.Adapter.XML.XMLAdapter(BH.oM.Adapter.FileSettings)")]
```

2023-10-25 15:27 UTC, FraserGreenroyd commented on XML_Adapter/XMLAdapter.cs
> +        [Description("Specify XML file and properties for data transfer.")]
I think this needs updating to something like `Connect to XML interoperability within the BHoM.`

2023-10-25 15:38 UTC, Tom-Kingstone commented
@BHoMBot check required
@BHoMBot check compliance

2023-10-25 16:05 UTC, FraserGreenroyd approved these changes
Looks good and aligns  nicely @Tom-Kingstone - great work

2023-10-26 10:05 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 18073278039

2023-10-26 10:05 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-10-26 10:07 UTC, merged